-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikibaseQualityConstraints/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wbqc_constraints (
  constraint_id SERIAL NOT NULL,
  constraint_guid TEXT NOT NULL,
  pid INT NOT NULL,
  constraint_type_qid TEXT NOT NULL,
  constraint_parameters TEXT DEFAULT NULL,
  PRIMARY KEY(constraint_id)
);

CREATE INDEX wbqc_constraints_pid_index ON wbqc_constraints (pid);

CREATE UNIQUE INDEX wbqc_constraints_guid_uniq ON wbqc_constraints (constraint_guid);
