-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikibaseQualityConstraints/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbqc_constraints (
  constraint_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  constraint_guid VARBINARY(63) NOT NULL,
  pid INT NOT NULL,
  constraint_type_qid VARBINARY(25) NOT NULL,
  constraint_parameters TEXT DEFAULT NULL,
  INDEX wbqc_constraints_pid_index (pid),
  UNIQUE INDEX wbqc_constraints_guid_uniq (constraint_guid),
  PRIMARY KEY(constraint_id)
) /*$wgDBTableOptions*/;
